// ===== PRODUCT DATA =====
const CATEGORIES = [
  { id: 'all',        name: 'الكل',                  icon: '🔧', count: 0 },
  { id: 'speakers',  name: 'ملفات السماعات',          icon: '🔊', count: 0 },
  { id: 'amplifier', name: 'أمبليفاير (ICs)',         icon: '📡', count: 0 },
  { id: 'transistor',name: 'ترانزستورات وموسفتات',   icon: '⚡', count: 0 },
  { id: 'ic',        name: 'دوائر متكاملة ICs',       icon: '💡', count: 0 },
  { id: 'resistor',  name: 'مقاومات وملفات',          icon: '🔩', count: 0 },
  { id: 'battery',   name: 'بطاريات ليثيوم',          icon: '🔋', count: 0 },
  { id: 'charging',  name: 'دوائر شحن وحماية',        icon: '🛡️', count: 0 },
  { id: 'car',       name: 'كاسيت السيارة',           icon: '🚗', count: 0 },
  { id: 'adapter',   name: 'أدابترات ومحولات',        icon: '🔌', count: 0 },
];

const PRODUCTS = [
  // ===== ملفات السماعات =====
  {
    id: 1, category: 'speakers',
    name: 'ملف سماعة 4 بوصة – 4 أوم',
    nameEn: 'Speaker Voice Coil 4" 4Ω',
    price: 25, oldPrice: null, badge: null,
    rating: 4.8, reviews: 124,
    img: 'imgs/vc4.jpg',
    desc: 'ملف سماعة عالي الجودة 4 بوصة مقاومة 4 أوم، مناسب لإصلاح وتجميع السماعات الصغيرة.',
    specs: ['4 بوصة', '4 أوم', 'تحمل عالي للحرارة', 'لفائف نحاس عالية النقاء'],
    inStock: true,
  },
  {
    id: 2, category: 'speakers',
    name: 'ملف سماعة 6 بوصة – 8 أوم',
    nameEn: 'Speaker Voice Coil 6" 8Ω',
    price: 35, oldPrice: 45, badge: 'sale',
    rating: 4.7, reviews: 89,
    img: 'imgs/vc6.jpg',
    desc: 'ملف سماعة 6 بوصة مقاومة 8 أوم، مناسب للسماعات المتوسطة الحجم.',
    specs: ['6 بوصة', '8 أوم', 'أداء صوتي ممتاز'],
    inStock: true,
  },
  {
    id: 3, category: 'speakers',
    name: 'ملف سماعة 8 بوصة – 4 أوم',
    nameEn: 'Speaker Voice Coil 8" 4Ω',
    price: 55, oldPrice: null, badge: 'hot',
    rating: 4.9, reviews: 213,
    img: 'imgs/vc8.jpg',
    desc: 'ملف سماعة 8 بوصة قوي، مناسب للسماعات المتوسطة إلى الكبيرة.',
    specs: ['8 بوصة', '4 أوم', 'قدرة 80 واط', 'مقاوم للحرارة'],
    inStock: true,
  },
  {
    id: 4, category: 'speakers',
    name: 'ملف سماعة 10 بوصة – 4 أوم',
    nameEn: 'Speaker Voice Coil 10" 4Ω',
    price: 75, oldPrice: null, badge: null,
    rating: 4.8, reviews: 67,
    img: 'imgs/vc10.jpg',
    desc: 'ملف سماعة 10 بوصة للمكبرات الكبيرة وأجهزة الصوت الاحترافية.',
    specs: ['10 بوصة', '4 أوم', 'قدرة 150 واط'],
    inStock: true,
  },
  {
    id: 5, category: 'speakers',
    name: 'ملف سماعة 12 بوصة – 8 أوم',
    nameEn: 'Speaker Voice Coil 12" 8Ω',
    price: 95, oldPrice: 120, badge: 'sale',
    rating: 4.9, reviews: 155,
    img: 'imgs/vc12.jpg',
    desc: 'ملف سماعة 12 بوصة احترافي للسبووفر والمكبرات الكبيرة.',
    specs: ['12 بوصة', '8 أوم', 'قدرة 200 واط', 'تصميم دوائري متين'],
    inStock: true,
  },
  {
    id: 6, category: 'speakers',
    name: 'ملف سماعة 15 بوصة – 4 أوم',
    nameEn: 'Speaker Voice Coil 15" 4Ω',
    price: 130, oldPrice: null, badge: 'new',
    rating: 5.0, reviews: 32,
    img: 'imgs/vc15.jpg',
    desc: 'ملف سماعة 15 بوصة للمكبرات الاحترافية والحفلات الكبيرة.',
    specs: ['15 بوصة', '4 أوم', 'قدرة 300 واط', 'جودة احترافية'],
    inStock: true,
  },

  // ===== أمبليفاير ICs =====
  {
    id: 7, category: 'amplifier',
    name: 'TDA2050 – مكبر صوت 32 واط',
    nameEn: 'TDA2050 Amplifier IC 32W',
    price: 18, oldPrice: null, badge: 'hot',
    rating: 4.8, reviews: 342,
    img: 'imgs/tda2050.jpg',
    desc: 'IC مكبر صوت TDA2050 عالي الجودة، 32 واط، مناسب للمكبرات المنزلية والصغيرة.',
    specs: ['32 واط', 'حزمة TO-220', 'ستريو', 'تشويه منخفض'],
    inStock: true,
  },
  {
    id: 8, category: 'amplifier',
    name: 'TDA7297 – مكبر ستريو 30 واط',
    nameEn: 'TDA7297 Stereo Amplifier 30W',
    price: 22, oldPrice: null, badge: null,
    rating: 4.7, reviews: 198,
    img: 'imgs/tda7297.jpg',
    desc: 'IC مكبر صوت ستريو TDA7297، 15+15 واط، مناسب للمكبرات الصغيرة.',
    specs: ['15+15 واط', 'ستريو', 'حماية من القصر'],
    inStock: true,
  },
  {
    id: 9, category: 'amplifier',
    name: 'TDA7498 – مكبر 100 واط D-Class',
    nameEn: 'TDA7498 Class-D Amplifier 100W',
    price: 45, oldPrice: 60, badge: 'sale',
    rating: 4.9, reviews: 87,
    img: 'imgs/tda7498.jpg',
    desc: 'IC مكبر فئة D عالي الكفاءة TDA7498، 100 واط، مناسب للمكبرات الكبيرة.',
    specs: ['100 واط', 'D-Class', 'كفاءة 90%', 'حرارة منخفضة'],
    inStock: true,
  },
  {
    id: 10, category: 'amplifier',
    name: 'LM3886 – مكبر أودي 68 واط',
    nameEn: 'LM3886 Audio Amplifier 68W',
    price: 35, oldPrice: null, badge: null,
    rating: 4.9, reviews: 156,
    img: 'imgs/lm3886.jpg',
    desc: 'IC مكبر صوت عالي الجودة LM3886، 68 واط، مفضل لمشاريع الأودي الاحترافية.',
    specs: ['68 واط', 'تشويه 0.03%', 'حماية حرارية', 'نطاق ترددي واسع'],
    inStock: true,
  },
  {
    id: 11, category: 'amplifier',
    name: 'TDA7265 – مكبر 25 واط ستريو',
    nameEn: 'TDA7265 Stereo 25W',
    price: 20, oldPrice: null, badge: 'new',
    rating: 4.6, reviews: 43,
    img: 'imgs/tda7265.jpg',
    desc: 'IC مكبر ستريو TDA7265، 25+25 واط، مناسب للمكبرات الصغيرة والمتوسطة.',
    specs: ['25+25 واط', 'ستريو', 'حماية من التشويه'],
    inStock: true,
  },

  // ===== ترانزستورات وموسفتات =====
  {
    id: 12, category: 'transistor',
    name: 'TIP41C – ترانزستور NPN 100V 6A',
    nameEn: 'TIP41C NPN Transistor',
    price: 8, oldPrice: null, badge: null,
    rating: 4.9, reviews: 412,
    img: 'imgs/tip41c.jpg',
    desc: 'ترانزستور NPN TIP41C، 100 فولت، 6 أمبير، مناسب للمكبرات والدوائر القوية.',
    specs: ['NPN', '100V', '6A', '65 واط', 'TO-220'],
    inStock: true,
  },
  {
    id: 13, category: 'transistor',
    name: 'TIP42C – ترانزستور PNP 100V 6A',
    nameEn: 'TIP42C PNP Transistor',
    price: 8, oldPrice: null, badge: null,
    rating: 4.9, reviews: 398,
    img: 'imgs/tip42c.jpg',
    desc: 'ترانزستور PNP TIP42C، مكمل TIP41C، 100 فولت، 6 أمبير.',
    specs: ['PNP', '100V', '6A', '65 واط', 'TO-220'],
    inStock: true,
  },
  {
    id: 14, category: 'transistor',
    name: '2N3055 – ترانزستور NPN قوي',
    nameEn: '2N3055 Power Transistor',
    price: 12, oldPrice: null, badge: 'hot',
    rating: 4.8, reviews: 267,
    img: 'imgs/2n3055.jpg',
    desc: 'ترانزستور قوي 2N3055 NPN، 60 فولت، 15 أمبير، كلاسيكي للمكبرات.',
    specs: ['NPN', '60V', '15A', '115 واط', 'TO-3'],
    inStock: true,
  },
  {
    id: 15, category: 'transistor',
    name: 'IRFZ44N – موسفت N-Channel 55V 49A',
    nameEn: 'IRFZ44N N-Channel MOSFET',
    price: 15, oldPrice: null, badge: null,
    rating: 4.9, reviews: 321,
    img: 'imgs/irfz44n.jpg',
    desc: 'موسفت IRFZ44N N-Channel، 55 فولت، 49 أمبير، مناسب للدوائر الإلكترونية القوية.',
    specs: ['N-Channel', '55V', '49A', 'مقاومة منخفضة RDS'],
    inStock: true,
  },
  {
    id: 16, category: 'transistor',
    name: 'IRF3205 – موسفت N-Channel 55V 110A',
    nameEn: 'IRF3205 N-Channel MOSFET',
    price: 20, oldPrice: null, badge: 'hot',
    rating: 4.9, reviews: 189,
    img: 'imgs/irf3205.jpg',
    desc: 'موسفت IRF3205 N-Channel، 55 فولت، 110 أمبير، للتطبيقات القوية جداً.',
    specs: ['N-Channel', '55V', '110A', 'RDS: 8mΩ'],
    inStock: true,
  },

  // ===== دوائر متكاملة ICs =====
  {
    id: 17, category: 'ic',
    name: 'NE555 – IC مؤقت متعدد الاستخدامات',
    nameEn: 'NE555 Timer IC',
    price: 5, oldPrice: null, badge: null,
    rating: 4.9, reviews: 678,
    img: 'imgs/ne555.jpg',
    desc: 'IC مؤقت NE555، أشهر IC في التاريخ، متعدد الاستخدامات للمؤقتات والأوسيليتور.',
    specs: ['DIP-8', 'تردد حتى 500KHz', 'تيار حتى 200mA'],
    inStock: true,
  },
  {
    id: 18, category: 'ic',
    name: 'LM317 – IC منظم جهد قابل للضبط',
    nameEn: 'LM317 Adjustable Regulator',
    price: 7, oldPrice: null, badge: null,
    rating: 4.8, reviews: 445,
    img: 'imgs/lm317.jpg',
    desc: 'IC منظم جهد قابل للضبط LM317، 1.2 إلى 37 فولت، 1.5 أمبير.',
    specs: ['1.2V - 37V', '1.5A', 'TO-220', 'دقة عالية'],
    inStock: true,
  },
  {
    id: 19, category: 'ic',
    name: 'LM7805 – IC منظم 5 فولت',
    nameEn: 'LM7805 5V Regulator',
    price: 5, oldPrice: null, badge: null,
    rating: 4.8, reviews: 512,
    img: 'imgs/lm7805.jpg',
    desc: 'IC منظم جهد LM7805، 5 فولت، 1 أمبير، مناسب لمعظم الدوائر الإلكترونية.',
    specs: ['5V ثابت', '1A', 'TO-220', 'حماية حرارية'],
    inStock: true,
  },
  {
    id: 20, category: 'ic',
    name: 'LM324 – IC مضخم عملياتي رباعي',
    nameEn: 'LM324 Quad Op-Amp',
    price: 6, oldPrice: null, badge: null,
    rating: 4.7, reviews: 234,
    img: 'imgs/lm324.jpg',
    desc: 'IC مضخم عملياتي رباعي LM324، مناسب لكثير من دوائر التحكم.',
    specs: ['4 مضخمات', 'DIP-14', '±16V', 'استهلاك منخفض'],
    inStock: true,
  },

  // ===== مقاومات وملفات =====
  {
    id: 21, category: 'resistor',
    name: 'مقاومات 1/4 واط – طقم 100 قطعة',
    nameEn: 'Resistor Set 1/4W 100pcs',
    price: 20, oldPrice: null, badge: 'hot',
    rating: 4.8, reviews: 321,
    img: 'imgs/resistors_kit.jpg',
    desc: 'طقم مقاومات 1/4 واط متنوعة القيم، 100 قطعة، مثالية لمشاريع الإلكترونيات.',
    specs: ['1/4 واط', '100 قطعة', 'قيم متنوعة', 'تسامح 5%'],
    inStock: true,
  },
  {
    id: 22, category: 'resistor',
    name: 'مقاومات 1 واط – عرض متنوع',
    nameEn: 'Resistors 1W Assorted',
    price: 30, oldPrice: null, badge: null,
    rating: 4.7, reviews: 145,
    img: 'imgs/resistors_1w.jpg',
    desc: 'مقاومات 1 واط متنوعة للدوائر القوية والمكبرات.',
    specs: ['1 واط', 'تسامح 5%', 'مناسب للمكبرات'],
    inStock: true,
  },
  {
    id: 23, category: 'resistor',
    name: 'مكثف كهربائي 2200µF 25V',
    nameEn: 'Capacitor 2200µF 25V',
    price: 8, oldPrice: null, badge: null,
    rating: 4.9, reviews: 287,
    img: 'imgs/cap2200.jpg',
    desc: 'مكثف كهربائي عالي الجودة 2200 ميكروفاراد، 25 فولت، لدوائر تصفية الجهد.',
    specs: ['2200µF', '25V', 'حياة طويلة', 'ألومنيوم'],
    inStock: true,
  },
  {
    id: 24, category: 'resistor',
    name: 'مكثف كهربائي 4700µF 35V',
    nameEn: 'Capacitor 4700µF 35V',
    price: 12, oldPrice: null, badge: null,
    rating: 4.8, reviews: 167,
    img: 'imgs/cap4700.jpg',
    desc: 'مكثف كهربائي 4700 ميكروفاراد، 35 فولت، للمكبرات والدوائر القوية.',
    specs: ['4700µF', '35V', 'حياة 5000 ساعة'],
    inStock: true,
  },

  // ===== بطاريات ليثيوم =====
  {
    id: 25, category: 'battery',
    name: 'حجر ليثيوم 18650 – 3.7V 2600mAh',
    nameEn: 'Li-ion 18650 2600mAh',
    price: 45, oldPrice: null, badge: 'hot',
    rating: 4.8, reviews: 456,
    img: 'imgs/18650.jpg',
    desc: 'بطارية ليثيوم أيون 18650، 3.7 فولت، 2600 مللي أمبير، للباور بنك والأجهزة.',
    specs: ['3.7V', '2600mAh', 'دورات شحن 500+', 'حماية داخلية'],
    inStock: true,
  },
  {
    id: 26, category: 'battery',
    name: 'حجر ليثيوم 21700 – 3.7V 4000mAh',
    nameEn: 'Li-ion 21700 4000mAh',
    price: 65, oldPrice: null, badge: 'new',
    rating: 4.9, reviews: 123,
    img: 'imgs/21700.jpg',
    desc: 'بطارية ليثيوم أيون 21700 سعة عالية، 4000 مللي أمبير، الجيل الجديد.',
    specs: ['3.7V', '4000mAh', 'تفريغ 10A', 'جيل جديد'],
    inStock: true,
  },
  {
    id: 27, category: 'battery',
    name: 'باك بطاريات 3S ليثيوم 11.1V',
    nameEn: 'Li-ion Pack 3S 11.1V',
    price: 150, oldPrice: 180, badge: 'sale',
    rating: 4.7, reviews: 67,
    img: 'imgs/pack3s.jpg',
    desc: 'باك بطاريات ليثيوم 3 خلايا 11.1 فولت مع دائرة BMS حماية.',
    specs: ['11.1V', 'BMS مدمج', 'تفريغ 20A', 'حماية كاملة'],
    inStock: true,
  },
  {
    id: 28, category: 'battery',
    name: 'باك بطاريات 4S ليثيوم 14.8V',
    nameEn: 'Li-ion Pack 4S 14.8V',
    price: 200, oldPrice: null, badge: null,
    rating: 4.8, reviews: 45,
    img: 'imgs/pack4s.jpg',
    desc: 'باك بطاريات ليثيوم 4 خلايا 14.8 فولت مع دائرة BMS.',
    specs: ['14.8V', 'BMS مدمج', 'تفريغ 20A'],
    inStock: true,
  },

  // ===== دوائر شحن وحماية =====
  {
    id: 29, category: 'charging',
    name: 'دائرة شحن TP4056 – 1A مع حماية',
    nameEn: 'TP4056 Charger Module 1A',
    price: 15, oldPrice: null, badge: 'hot',
    rating: 4.9, reviews: 634,
    img: 'imgs/tp4056.jpg',
    desc: 'وحدة شحن ليثيوم TP4056 مع دائرة حماية، 1 أمبير، منفذ Micro-USB.',
    specs: ['1A', 'Micro-USB', 'حماية من القصر', 'LED مؤشر'],
    inStock: true,
  },
  {
    id: 30, category: 'charging',
    name: 'دائرة BMS حماية 3S – 25A',
    nameEn: 'BMS 3S Protection 25A',
    price: 35, oldPrice: null, badge: null,
    rating: 4.8, reviews: 178,
    img: 'imgs/bms3s.jpg',
    desc: 'دائرة إدارة وحماية بطاريات BMS ثلاث خلايا، 25 أمبير، حماية شاملة.',
    specs: ['3S', '25A', 'حماية زيادة شحن', 'حماية تفريغ عميق'],
    inStock: true,
  },
  {
    id: 31, category: 'charging',
    name: 'دائرة BMS حماية 4S – 20A',
    nameEn: 'BMS 4S Protection 20A',
    price: 40, oldPrice: null, badge: null,
    rating: 4.7, reviews: 89,
    img: 'imgs/bms4s.jpg',
    desc: 'دائرة BMS لأربع خلايا ليثيوم، 20 أمبير، لحماية باكات البطاريات.',
    specs: ['4S', '20A', 'موازنة الخلايا', 'حماية حرارية'],
    inStock: true,
  },
  {
    id: 32, category: 'charging',
    name: 'محول DC-DC Step-Up Boost 2A',
    nameEn: 'DC-DC Boost Converter 2A',
    price: 25, oldPrice: null, badge: 'new',
    rating: 4.8, reviews: 134,
    img: 'imgs/boost.jpg',
    desc: 'محول رفع الجهد DC-DC، مدخل 2-24V، مخرج 5-28V، 2 أمبير.',
    specs: ['مدخل 2-24V', 'مخرج 5-28V', '2A', 'كفاءة 93%'],
    inStock: true,
  },

  // ===== كاسيت السيارة =====
  {
    id: 33, category: 'car',
    name: 'رأس كاسيت سيارة بلوتوث AUX',
    nameEn: 'Car Cassette Bluetooth AUX',
    price: 120, oldPrice: 150, badge: 'sale',
    rating: 4.7, reviews: 234,
    img: 'imgs/car_cassette.jpg',
    desc: 'رأس كاسيت سيارة مع بلوتوث وAUX وUSB، مناسب لجميع أنواع السيارات.',
    specs: ['بلوتوث 5.0', 'AUX', 'USB', 'SD Card'],
    inStock: true,
  },
  {
    id: 34, category: 'car',
    name: 'مكبر صوت سيارة 4 قنوات 200W',
    nameEn: 'Car Amplifier 4CH 200W',
    price: 280, oldPrice: null, badge: null,
    rating: 4.8, reviews: 89,
    img: 'imgs/car_amp.jpg',
    desc: 'مكبر صوت سيارة 4 قنوات، 200 واط، مناسب للسيارات والتجميعات.',
    specs: ['4 قنوات', '200 واط', '12V', 'تشويه منخفض'],
    inStock: true,
  },
  {
    id: 35, category: 'car',
    name: 'سماعة سيارة كوكسيال 6.5 بوصة',
    nameEn: 'Car Speaker Coaxial 6.5"',
    price: 85, oldPrice: null, badge: null,
    rating: 4.6, reviews: 156,
    img: 'imgs/car_speaker.jpg',
    desc: 'سماعة سيارة كوكسيال 6.5 بوصة، 120 واط، صوت نقي واضح.',
    specs: ['6.5 بوصة', '120 واط', '4 أوم', 'كوكسيال'],
    inStock: true,
  },

  // ===== أدابترات ومحولات =====
  {
    id: 36, category: 'adapter',
    name: 'أدابتر 12V 2A – DC Jack',
    nameEn: 'Power Adapter 12V 2A',
    price: 35, oldPrice: null, badge: null,
    rating: 4.7, reviews: 312,
    img: 'imgs/adapter12v.jpg',
    desc: 'أدابتر جهد 12 فولت، 2 أمبير، مناسب للراوترات والدوائر الإلكترونية.',
    specs: ['12V', '2A', 'DC Jack 5.5mm', 'محمي من القصر'],
    inStock: true,
  },
  {
    id: 37, category: 'adapter',
    name: 'أدابتر 5V 3A – USB-C',
    nameEn: 'Power Adapter 5V 3A USB-C',
    price: 45, oldPrice: null, badge: 'new',
    rating: 4.8, reviews: 123,
    img: 'imgs/adapter5v.jpg',
    desc: 'أدابتر شحن 5 فولت، 3 أمبير، منفذ USB-C، مناسب للأجهزة الحديثة.',
    specs: ['5V', '3A', 'USB-C', '15 واط'],
    inStock: true,
  },
  {
    id: 38, category: 'adapter',
    name: 'أدابتر قابل للضبط 3V-24V 3A',
    nameEn: 'Variable Power Adapter 3-24V',
    price: 75, oldPrice: 95, badge: 'sale',
    rating: 4.9, reviews: 78,
    img: 'imgs/adapter_var.jpg',
    desc: 'أدابتر جهد قابل للضبط من 3 إلى 24 فولت، 3 أمبير، مثالي لورش العمل.',
    specs: ['3V-24V', '3A', 'عرض رقمي', 'حماية شاملة'],
    inStock: true,
  },
];

// Update category counts
CATEGORIES.forEach(cat => {
  if (cat.id === 'all') {
    cat.count = PRODUCTS.length;
  } else {
    cat.count = PRODUCTS.filter(p => p.category === cat.id).length;
  }
});

// Export
if (typeof module !== 'undefined') {
  module.exports = { PRODUCTS, CATEGORIES };
}
